name: Publish Test Results

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout Code

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'



    - name: Publish Test Results
      uses: actions/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          test-results/**/*.xml
          test-results/**/*.trx
          test-results/**/*.json
          

          - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            pip install pytest
    
    - name: Run Tests
      run: |
        pytest

    - name: Publish Test Results
      id: publish_test_results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: '**/test-results.xml'
