# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  checkov_scan_and_upload_results:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Passen Sie die Python-Version an Ihre Bedürfnisse an

      - name: Install dependencies
        run: |
          pip install checkov
          pip install gitpython

      - name: Run Checkov scan
        run: |
          checkov --directory .

      - name: Create and upload test results branch
        run: |
          import os
          from git import Repo

          pr_branch_name = os.getenv("GITHUB_HEAD_REF")
          test_results_branch_name = f"{pr_branch_name}_testresults"
          
          repo = Repo(os.getcwd())
          repo.create_head(test_results_branch_name)
          repo.heads[test_results_branch_name].set_tracking_branch(repo.remotes.origin)
          repo.heads[test_results_branch_name].checkout()

          # Hier können Sie weitere Aktionen hinzufügen, um die Testergebnisse in den Branch zu committen und zu pushen,
          # z.B. die Ausgabe von Checkov in eine Datei speichern und diese Datei committen.

          print(f"Created branch '{test_results_branch_name}' based on PR branch '{pr_branch_name}'.")
