name: CI

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]
  workflow_dispatch:

jobs:
  checkov_scan_and_upload_results:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install checkov
          pip install gitpython

      - name: Run Checkov scan
        run: |
          checkov --directory . --fail-on HIGH,CRITICAL
          
      - name: Create and upload test results branch
        run: |
          import os
          from git import Repo
          pr_branch_name = os.getenv("GITHUB_HEAD_REF")
          test_results_branch_name = f"{pr_branch_name}_testresults"
          
          repo = Repo(os.getcwd())
          repo.create_head(test_results_branch_name)
          repo.heads[test_results_branch_name].set_tracking_branch(repo.remotes.origin)
          repo.heads[test_results_branch_name].checkout()
          # Fügen Sie hier den Code hinzu, um die Testergebnisse in den Branch zu committen und zu pushen.
          print(f"Created branch '{test_results_branch_name}' based on PR branch '{pr_branch_name}'.")
