name: CI

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]
  workflow_dispatch:
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  checkov_scan_and_upload_results:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install checkov
          pip install gitpython

      - name: Run Checkov scan
        run: |
          checkov --directory .  -o junitxml > checkov_results.xml
      - name: Display Directory Contents and File Content
        if: always()
        run: |
          echo "Listing directory contents:"
          ls -la          
          echo "Displaying content of a specific file:"
          cat ./checkov_results.json

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: checkov_results.xml

