name: CI

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]
  workflow_dispatch:
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  checkov_scan_and_upload_results:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Get Start time
        id: starttime
        if: always()
        run: |
            start=$(date +%s)
            echo "$start" > start_time.txt # Speichern Sie die Startzeit in einer Datei

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install checkov
          pip install gitpython

      - name: Run Checkov scan
        run: |
          checkov --directory .  -o junitxml > checkov_results.xml



      - name: Calculate Execution Time and Update JUnit XML
        if: always()
        run: |
            csv_file="checkov_results.xml"

            # Lesen der zweiten Zeile und Ersetzen von 'time="0.0"' durch 'time="${EXECUTION_TIME}''
            second_line=$(sed -n 2p "$csv_file")
            new_second_line=$(echo "$second_line" | sed "s/time=\"0.0\"/time=\"${EXECUTION_TIME}\"/")
            # Ausgabe der neuen Zeile (optional)
            echo "$new_second_line"
            # Optional: Die neue Zeile wieder in die Datei schreiben
            echo "$new_second_line" >> temp && mv temp "$csv_file"
            #echo "$UPDATED_JUNIT_XML" > checkov_results.xml
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: checkov_results.xml
      - name: Display Directory Contents and File Content
        if: always()
        run: |
            echo "Listing directory contents:"
            ls -la          
            echo "Displaying"
            cat ./checkov_results.xml