name: CI

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]
  workflow_dispatch:
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  checkov_scan_and_upload_results:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install checkov
          pip install gitpython

      - name: Run Checkov scan
        run: |
          checkov --directory . 

          # Schritt: Convert Checkov output to JSON
      - name: Convert Checkov output to JSON
        if: always()
        run: |
          python -c "
          import xml.etree.ElementTree as ET
          import json
      
          tree = ET.parse('checkov.out.xml')
          root = tree.getroot()
      
          findings = []
          for finding in root.findall('.//finding'):
              item = {}
              for child in finding:
                  item[child.tag] = child.text
              findings.append(item)
      
          with open('checkov_output.json', 'w') as f:
              json.dump(findings, f)
          "

          - name: Publish Test Results
            uses: EnricoMi/publish-unit-test-result-action@v2
            if: always()
            with:
              files: checkov_output.json

